#
# GitHub Action Workflow for building the UEFI debugger extension.
#
# Copyright (c) Microsoft Corporation
#
# SPDX-License-Identifier: BSD-2-Clause-Patent
#

name: "Build UEFI Debug Extension"

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]
        platform: [x64, arm64]
    runs-on: windows-2022
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Setup MsBuild
        uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2.0.0

      - name: Setup NuGet
        uses: nuget/setup-nuget@d105a947828025cd7a980103c35ba2bfae586d0f # v2.0.2

      - name: Setup node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: '22'

      - name: Restore EfiSymComposition NuGet packages
        run: nuget restore EfiSymComposition\packages.config -PackagesDirectory EfiSymComposition\packages

      - name: Build DLL
        run: msbuild UefiDbgExt\uefiext.vcxproj -property:Configuration=${{ matrix.configuration }} -property:Platform=${{ matrix.platform }}

      - name: Build EfiSymComposition DLL
        run: msbuild EfiSymComposition\EfiSymComposition.vcxproj -property:Configuration=${{ matrix.configuration }} -property:Platform=${{ matrix.platform }}

      - name: Publish Binary
        if: ${{ matrix.configuration == 'Release' && github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: UefiDbgExt-${{ matrix.platform }}-${{ matrix.configuration }}
          path: |
            UefiDbgExt\${{ matrix.platform }}\${{ matrix.configuration }}\uefiext.dll
            EfiSymComposition\${{ matrix.platform }}\${{ matrix.configuration }}\EfiSymComposition.dll

      - name: Publish Release Asset
        if: ${{ matrix.configuration == 'Release' && github.event_name == 'release' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Compress-Archive -Path UefiDbgExt\${{ matrix.platform }}\${{ matrix.configuration }}\uefiext.dll, EfiSymComposition\${{ matrix.platform }}\${{ matrix.configuration }}\EfiSymComposition.dll -DestinationPath UefiExt_${{ matrix.platform }}.zip
          gh release upload ${{ github.event.release.tag_name }} UefiExt_${{ matrix.platform }}.zip
