#
# GitHub Action Workflow for building the UEFI debugger extension.
#
# Copyright (c) Microsoft Corporation
#
# SPDX-License-Identifier: BSD-2-Clause-Patent
#

name: "Build UEFI Debug Extension"

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]
        platform: [x64, arm64]
    runs-on: windows-2022
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup MsBuild
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0

      - name: Setup NuGet
        uses: nuget/setup-nuget@b26b823c478ee115be5c9403e62c90b0bf943843 # v3.1.0

      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '22'

      - name: Restore EfiSymComposition NuGet packages
        run: nuget restore EfiSymComposition\packages.config -PackagesDirectory EfiSymComposition\packages

      - name: Build DLL
        run: msbuild UefiDbgExt\uefiext.vcxproj -property:Configuration=${{ matrix.configuration }} -property:Platform=${{ matrix.platform }}

      - name: Build EfiSymComposition DLL
        run: msbuild EfiSymComposition\EfiSymComposition.vcxproj -property:Configuration=${{ matrix.configuration }} -property:Platform=${{ matrix.platform }}

      - name: Publish Binary
        if: ${{ matrix.configuration == 'Release' && github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: UefiDbgExt-${{ matrix.platform }}-${{ matrix.configuration }}
          path: |
            UefiDbgExt\${{ matrix.platform }}\${{ matrix.configuration }}\uefiext.dll
            EfiSymComposition\${{ matrix.platform }}\${{ matrix.configuration }}\EfiSymComposition.dll

      - name: Publish Release Asset
        if: ${{ matrix.configuration == 'Release' && github.event_name == 'release' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Compress-Archive -Path UefiDbgExt\${{ matrix.platform }}\${{ matrix.configuration }}\uefiext.dll, EfiSymComposition\${{ matrix.platform }}\${{ matrix.configuration }}\EfiSymComposition.dll -DestinationPath UefiExt_${{ matrix.platform }}.zip
          gh release upload ${{ github.event.release.tag_name }} UefiExt_${{ matrix.platform }}.zip
